name: waveform_extractor
description: A new Flutter plugin project.
version: 1.0.0
homepage: https://github.com/namidaco/waveform_extractor/blob/main/README.md
repository: https://github.com/namidaco/waveform_extractor

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.namidaco.waveform_extractor
        pluginClass: WaveformExtractorPlugin
